### ISSUE TITLE
reproducing language modeling results

### ISSUE THREAD

**Issue by tonytan48** [ChengyueGongR/advsoft#3]
Hi Mr.Gong, congradulate on your work on new language modeling technique. I was trying to reproduce your experiment but some error of the dictionary occured:
![image](https://user-images.githubusercontent.com/10150598/90500490-8b276d80-e17d-11ea-9680-5c79af95210c.png)
If I substitute the data.py from original mos repo, like "import data_mos as data" the following error occurs:
![image](https://user-images.githubusercontent.com/10150598/90501002-43edac80-e17e-11ea-8dc6-780537383423.png)

May I ask for the solution for this? I am not sure is the problem of tokenization part "data.py" or the embedding_regularization part.

Best,
Qingyu Tan

**Comment by tonytan48** [comment]
Thank you for the prompt reply. 

After pulling the latest branch with the updated "data.py". I still have an error of :
Traceback (most recent call last):
  File "main.py", line 285, in <module>
    train()
  File "main.py", line 228, in train
    log_prob, hidden[s_id], rnn_hs, dropped_rnn_hs = parallel_model(cur_data, hidden[s_id], return_h=True, targets=cur_targets, is_switch=is_switch)
  File "/home/qingyu.tan/miniconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/qingyu.tan/projects/advsoft/mos-awd-lstm-lm/model.py", line 83, in forward
    emb, sigma = embedded_dropout(self.encoder, torch.ones_like(self.encoder.weight), input, dropout=self.dropoute if (self.training and self.use_dropout) else 0, is_training=self.training)
  File "/home/qingyu.tan/projects/advsoft/mos-awd-lstm-lm/embed_regularize.py", line 34, in embedded_dropout
    X = embed._backend.Embedding.apply(words, masked_embed_weight,
  File "/home/qingyu.tan/miniconda3/envs/py36/lib/python3.6/site-packages/torch/nn/backends/backend.py", line 10, in __getattr__
    raise NotImplementedError

May I know can you reproduce the error? 
My torch version is 0.4.1.post2
